/**
 * article action type constants values
 */
export const articleActionTypes = {
  ACTION_GET_ARTICLES_REQUEST: 'ACTION_GET_ARTICLES_REQUEST',
  ACTION_GET_ARTICLES_SUCCESS: 'ACTION_GET_ARTICLES_SUCCESS',
  ACTION_GET_ARTICLES_FAILURE: 'ACTION_GET_ARTICLES_FAILURE',
  ACTION_DELETE_ARTICLE_REQUEST: 'ACTION_DELETE_ARTICLE_REQUEST',
  ACTION_DELETE_ARTICLE_SUCCESS: 'ACTION_DELETE_ARTICLE_SUCCESS',
  ACTION_DELETE_ARTICLE_FAILURE: 'ACTION_DELETE_ARTICLE_FAILURE',
  ACTION_CREATE_ARTICLE_REQUEST: 'ACTION_CREATE_ARTICLE_REQUEST',
  ACTION_CREATE_ARTICLE_SUCCESS: 'ACTION_CREATE_ARTICLE_SUCCESS',
  ACTION_CREATE_ARTICLE_FAILURE: 'ACTION_CREATE_ARTICLE_SUCCESS'
};
