/**
 * WEATHER CHANNEL action type constants values
 */
export const channelActionTypes = {
  ACTION_CREATE_CHANNEL_REQUEST: 'ACTION_CREATE_CHANNEL_REQUEST',
  ACTION_CREATE_CHANNEL_SUCCESS: 'ACTION_CREATE_CHANNEL_SUCCESS',
  ACTION_CREATE_CHANNEL_FAILURE: 'ACTION_CREATE_CHANNEL_FAILURE',

  ACTION_GET_CHANNEL_REQUEST: 'ACTION_GET_CHANNEL_REQUEST',
  ACTION_GET_CHANNEL_SUCCESS: 'ACTION_GET_CHANNEL_SUCCESS',
  ACTION_GET_CHANNEL_FAILURE: 'ACTION_GET_CHANNEL_FAILURE',

  ACTION_DELETE_CHANNEL_REQUEST: 'ACTION_DELETE_CHANNEL_REQUEST',
  ACTION_DELETE_CHANNEL_SUCCESS: 'ACTION_DELETE_CHANNEL_SUCCESS',
  ACTION_DELETE_CHANNEL_FAILURE: 'ACTION_DELETE_CHANNEL_FAILURE',
};
