/**
 * FACEBOOK action type constants values
 */
export const facebookActionTypes = {
  ACTION_FACEBOOK_PLACE_REQUEST: 'ACTION_FACEBOOK_PLACE_REQUEST',
  ACTION_FACEBOOK_PLACE_SUCCESS: 'ACTION_FACEBOOK_PLACE_SUCCESS',
  ACTION_FACEBOOK_PLACE_FAILURE: 'ACTION_FACEBOOK_PLACE_FAILURE'
};
