/**
 * user action type constants values
 */
export const userActionTypes = {
  ACTION_USER_SIGNUP_REQUEST: 'ACTION_USER_SIGNUP_REQUEST',
  ACTION_USER_SIGNUP_SUCCESS: 'ACTION_USER_SIGNUP_SUCCESS',
  ACTION_USER_SIGNUP_FAILURE: 'ACTION_USER_SIGNUP_FAILURE',

  ACTION_USER_LOGIN_REQUEST: 'ACTION_USER_LOGIN_REQUEST',
  ACTION_USER_LOGIN_SUCCESS: 'ACTION_USER_LOGIN_SUCCESS',
  ACTION_USER_LOGIN_FAILURE: 'ACTION_USER_LOGIN_FAILURE',

  ACTION_USER_LOGOUT: 'ACTION_USER_LOGOUT',

  ACTION_USER_WITHDRAWAL_REQUEST: 'ACTION_USER_WITHDRAWAL_REQUEST',
  ACTION_USER_WITHDRAWAL_SUCCESS: 'ACTION_USER_WITHDRAWAL_SUCCESS',
  ACTION_USER_WITHDRAWAL_FAILURE: 'ACTION_USER_WITHDRAWAL_FAILURE'
};
