/**
 * WEATHER action type constants values
 */
export const weatherActionTypes = {
  ACTION_WEATHER_REQUEST: 'ACTION_WEATHER_REQUEST',
  ACTION_WEATHER_SUCCESS: 'ACTION_WEATHER_SUCCESS',
  ACTION_WEATHER_EMPTY: 'ACTION_WEATHER_EMPTY',
  ACTION_WEATHER_FAILURE: 'ACTION_WEATHER_FAILURE'
};
